-- SQL para criar a tabela de histórico de conversas capturadas
CREATE TABLE IF NOT EXISTS public."Dados_messageRecebida" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    contato text,
    texto_digitado text,
    historico_mensagens text[], -- Array de texto para as últimas mensagens
    timestamp_extensao timestamp with time zone
);

-- Comentários para identificar a finalidade
COMMENT ON TABLE public."Dados_messageRecebida" IS 'Armazena os dados capturados pela extensão quando o botão Processar é clicado.';

-- Habilitar RLS (Opcional, mas recomendado se não for usar apenas service_role)
ALTER TABLE public."Dados_messageRecebida" ENABLE ROW LEVEL SECURITY;

-- Criar política de acesso total para service_role (usada no backend)
CREATE POLICY "Acesso total para service_role" ON public."Dados_messageRecebida"
    FOR ALL 
    TO service_role
    USING (true)
    WITH CHECK (true);
